<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="UserProfile.aspx.cs" Inherits="Beans_Stock_Management.UserProfile" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <style type="text/css">
        body{
            background-color:#311432;
        }
    </style>

    <form id="form1" runat="server">
        <div>
            <asp:Button ID="logoutBtn" runat="server" Text="Logout" OnClick="logoutBtn_Click" Height="38px" Width="96px"/>
            <br /><br /><br /><br />
            <table style="margin-left: auto; margin-right: auto;">
                <tr style="height: 50px">
                    <td style="width: 55%">
                        <asp:Label ID="usernameL" runat="server" Text="Username" Font-Names="Poppins Light" Font-Size="20px" ForeColor="FloralWhite"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="usernameTB" runat="server" Font-Names="Poppins Light" Font-Size="18px"></asp:TextBox>
                    </td>
                </tr>
                <tr style="height: 50px">
                    <td style="width: 55%">
                        <asp:Label ID="fullnameL" runat="server" Text="Full name" Font-Names="Poppins Light" Font-Size="20px" ForeColor="FloralWhite"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="fullnameTB" runat="server" Font-Names="Poppins Light" Font-Size="18px"></asp:TextBox>
                    </td>
                </tr>
                <tr style="height: 50px">
                    <td style="width: 55%">
                        <asp:Label ID="contactL" runat="server" Text="Contact" Font-Names="Poppins Light" Font-Size="20px" ForeColor="FloralWhite"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="contactTB" runat="server" Font-Names="Poppins Light" Font-Size="18px" TextMode="Number"></asp:TextBox>
                    </td>
                </tr>
                <tr style="height: 50px">
                    <td style="width: 55%">
                        <asp:Label ID="passwordL" runat="server" Text="Password" Font-Names="Poppins Light" Font-Size="20px" ForeColor="FloralWhite"></asp:Label>
                    </td>
                    <td>
                        <asp:TextBox ID="passwordTB" runat="server" Font-Names="Poppins Light" Font-Size="18px" TextMode="Password"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <asp:Button ID="addBtn" runat="server" Text="Add" Font-Size="18px" Height="38px" Width="96px" OnClick="addBtn_Click" />
                        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:StockConnection %>" DeleteCommand="DELETE FROM [UserTable] WHERE [username] = @username" InsertCommand="INSERT INTO [UserTable] ([username], [fullname], [contact], [password]) VALUES (@username, @fullname, @contact, @password)" SelectCommand="SELECT * FROM [UserTable]" UpdateCommand="UPDATE [UserTable] SET [fullname] = @fullname, [contact] = @contact, [password] = @password WHERE [username] = @username">
                            <DeleteParameters>
                                <asp:Parameter Name="username" Type="String" />
                            </DeleteParameters>
                            <InsertParameters>
                                <asp:Parameter Name="username" Type="String" />
                                <asp:Parameter Name="fullname" Type="String" />
                                <asp:Parameter Name="contact" Type="String" />
                                <asp:Parameter Name="password" Type="String" />
                            </InsertParameters>
                            <UpdateParameters>
                                <asp:Parameter Name="fullname" Type="String" />
                                <asp:Parameter Name="contact" Type="String" />
                                <asp:Parameter Name="password" Type="String" />
                                <asp:Parameter Name="username" Type="String" />
                            </UpdateParameters>
                        </asp:SqlDataSource>
                    </td>
                </tr>
            </table>
            <br /><br />
        </div>
        <div style="margin-left:100px; margin-right:100px">
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="username" DataSourceID="SqlDataSource1" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" Height="100%" Width="100%" Font-Size="16px" BackColor="LightGray"  BorderColor="#2f4c66" BorderStyle="Solid">
                <Columns>
                    <asp:BoundField DataField="username" HeaderText="Username" ReadOnly="True" SortExpression="username" ItemStyle-HorizontalAlign="Center" HeaderStyle-CssClass="text-center" HeaderStyle-ForeColor="#507ca3"/>
                    <asp:BoundField DataField="fullname" HeaderText="Fullname" SortExpression="fullname" ItemStyle-HorizontalAlign="Center" HeaderStyle-CssClass="text-center" HeaderStyle-ForeColor="#507ca3"/>
                    <asp:BoundField DataField="contact" HeaderText="Contact" SortExpression="contact" ItemStyle-HorizontalAlign="Center" HeaderStyle-CssClass="text-center" HeaderStyle-ForeColor="#507ca3"/>
                    <asp:BoundField DataField="password" HeaderText="Password" SortExpression="password" ItemStyle-HorizontalAlign="Center" HeaderStyle-CssClass="text-center" HeaderStyle-ForeColor="#507ca3"/>
                </Columns>
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:StockConnection %>" SelectCommand="SELECT * FROM [UserTable]" DeleteCommand="delete from [UserTable] where username = @username" UpdateCommand="update [UserTable] set username = @username, fullname = @fullname, contact = @contact, password = @password where username = @username"></asp:SqlDataSource>
        </div>
    </form>
</body>
</html>
